export type ItemType = 'Weapon' | 'Potion' | 'Material' | 'Armor' | 'Helmet';

export interface Item {
  id: string;
  name: string;
  type: ItemType;
  description: string;
  price: number;
  stackable: boolean;
  icon?: string;
  size?: { x: number; y: number };
  worldSize?: { x: number; y: number };
  inventorySize?: { x: number; y: number };
  quickBarSize?: { x: number; y: number };
}

export interface Weapon extends Item {
  type: 'Weapon';
  atk: number;
  range: number;
  swingArc: number;
  speed: number;
  weaponType: 'Sword' | 'Spear' | 'Bow';
}

export interface Potion extends Item {
  type: 'Potion';
  hpRestore?: number;
  mpRestore?: number;
  hpRestorePercent?: number; // 0.1 for 10%
  mpRestorePercent?: number; // 0.1 for 10%
}

export interface Armor extends Item {
  type: 'Armor';
  def: number;
}

export interface Helmet extends Item {
  type: 'Helmet';
  def: number;
}

export const ITEM_DATABASE: Record<string, Item> = {
  basic_sword: {
    id: 'basic_sword',
    name: 'Old Sword',
    type: 'Weapon',
    description: 'A worn-out sword, heavy but still sharp enough to cut.',
    price: 10,
    stackable: false,
    atk: 12,
    range: 85,
    speed: 0.4,
    weaponType: 'Sword',
    icon: 'assets/Items/BasicSword.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Weapon,
  long_spear: {
    id: 'long_spear',
    name: 'Broken Spear',
    type: 'Weapon',
    description: 'A broken wooden spear with decent reach.',
    price: 15,
    stackable: false,
    atk: 18,
    range: 200,
    speed: 2.5,
    weaponType: 'Spear',
    icon: 'assets/Items/LongSpear.png',
    size: { x: 40, y: 40 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Weapon,
  iron_sword: {
    id: 'iron_sword',
    name: 'Iron Sword',
    type: 'Weapon',
    description: 'A well-forged, sturdy iron sword.',
    price: 100,
    stackable: false,
    atk: 80, // Increased from 60
    range: 110,
    speed: 4.0,
    weaponType: 'Sword',
    icon: 'assets/Items/IronSword.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Weapon,
  old_armor: {
    id: 'old_armor',
    name: 'Old Armor',
    type: 'Armor',
    description: 'Rusty in places, but enough to provide some protection.',
    price: 50,
    stackable: false,
    def: 10, // Increased from 5
    icon: 'assets/Items/OldArmor.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Armor,
  slime_jelly: {
    id: 'slime_jelly',
    name: 'Slime Jelly',
    type: 'Material',
    description: 'Sticky remains of a defeated slime.',
    price: 60,
    stackable: true,
    icon: 'assets/Items/SlimeJelly.png',
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 128, y: 128 },
  },
  bat_wing: {
    id: 'bat_wing',
    name: 'Bat Wing',
    type: 'Material',
    description: 'Thin, leathery wing from a bat.',
    price: 100,
    stackable: true,
    icon: 'assets/Items/BatWing.png',
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  },
  // Proxima Luna Materials
  phase_lens: {
    id: 'phase_lens',
    name: 'Phase Lens',
    type: 'Material',
    description:
      'A lens extracted from a Quantum Wraith. It refracts light strangely.',
    price: 200,
    stackable: true,
    icon: 'assets/Items/PhaseLens.png',
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  },
  plasma_core: {
    id: 'plasma_core',
    name: 'Plasma Core',
    type: 'Material',
    description:
      'The power source of an Optical Sentinel. It still hums with energy.',
    price: 300,
    stackable: true,
    icon: 'assets/Items/PlasmaCore.png',
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  },
  grav_essence: {
    id: 'grav_essence',
    name: 'Gravity Essence',
    type: 'Material',
    description:
      'Condensed essence of Gravity Drifter fluids. It has the property of attracting surrounding objects.',
    price: 350,
    stackable: true,
    icon: 'assets/Items/GravEssence.png',
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  },
  void_shard: {
    id: 'void_shard',
    name: 'Void Shard',
    type: 'Material',
    description:
      'A shard left behind by a Star Eater. It exudes a chilling darkness.',
    price: 500,
    stackable: true,
    icon: 'assets/Items/VoidShard.png',
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  },
  overseer_heart: {
    id: 'overseer_heart',
    name: "Overseer's Heart",
    type: 'Material',
    description:
      "The central control unit of the Luna Overseer. It emits a faint light as if it's pulsing.",
    price: 5000,
    stackable: true,
    icon: 'assets/Items/OverseerHeart.png',
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  },
  red_potion: {
    id: 'red_potion',
    name: 'Red Potion',
    type: 'Potion',
    description: 'A potion that restores 10% of Max HP.',
    price: 30, // Increased price for percentage level scaling
    stackable: true,
    hpRestorePercent: 0.1,
    icon: 'assets/Items/RedPotion.png',
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Potion,
  blue_potion: {
    id: 'blue_potion',
    name: 'Blue Potion',
    type: 'Potion',
    description: 'A potion that restores 50 MP.',
    price: 30,
    stackable: true,
    mpRestore: 50,
    icon: 'assets/Items/BluePotion.png',
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Potion,
  return_scroll: {
    id: 'return_scroll',
    name: 'Return Scroll',
    type: 'Potion',
    description: 'Instantly transports you back to the village.',
    price: 50,
    stackable: true,
    icon: 'assets/Items/ReturnScroll.png',
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Potion,
  enhance_stone: {
    id: 'enhance_stone',
    name: 'Enhancement Stone',
    type: 'Material',
    description: 'A mysterious stone used to enhance equipment.',
    price: 100,
    stackable: true,
    icon: 'assets/Items/EnhanceStone.png',
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  },
  frost_blade: {
    id: 'frost_blade',
    name: 'Frost Blade',
    type: 'Weapon',
    description:
      'A cold sword covered in frost. You can feel the breath of the Frost Dragon.',
    price: 5500,
    stackable: false,
    atk: 380, // Decreased from 450 to control power creep
    range: 150,
    speed: 5.0,
    weaponType: 'Sword',
    icon: 'assets/Items/FrostBlade.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Weapon,
  frost_armor: {
    id: 'frost_armor',
    name: 'Frost Armor',
    type: 'Armor',
    description: 'Sturdy armor made from the scales of a Frost Dragon.',
    price: 5200,
    stackable: false,
    def: 45, // Increased from 25
    icon: 'assets/Items/FrostArmor.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Armor,
  // Proxima Luna Equipment
  pulse_blade: {
    id: 'pulse_blade',
    name: 'Pulse Blade',
    type: 'Weapon',
    description:
      'A pulse sword for apprentice cadets, flowing with blue energy.',
    price: 800,
    stackable: false,
    atk: 200, // Increased from 120
    range: 150,
    speed: 4.5,
    weaponType: 'Sword',
    swingArc: 90,
    icon: 'assets/Items/PulseBlade.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Weapon,
  titanium_armor: {
    id: 'titanium_armor',
    name: 'Titanium Armor',
    type: 'Armor',
    description:
      'Lightweight and durable titanium alloy armor for space exploration.',
    price: 600,
    stackable: false,
    def: 20, // Increased from 10
    icon: 'assets/Items/TitaniumArmor.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Armor,
  luna_goggles: {
    id: 'luna_goggles',
    name: 'Luna Goggles',
    type: 'Helmet',
    description:
      'Exploration goggles that provide visibility even in the darkness of Proxima Luna.',
    price: 300,
    stackable: false,
    def: 15, // Increased from 8
    icon: 'assets/Items/LunaGoggles.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Helmet,
  // Basic Helmets
  leather_cap: {
    id: 'leather_cap',
    name: 'Leather Cap',
    type: 'Helmet',
    description: 'A simple protective cap made of leather.',
    price: 50,
    stackable: false,
    def: 6, // Increased from 3
    icon: 'assets/Items/LeatherCap.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Helmet,
  iron_helmet: {
    id: 'iron_helmet',
    name: 'Iron Helmet',
    type: 'Helmet',
    description: 'A sturdy helmet made of iron.',
    price: 200,
    stackable: false,
    def: 10, // Increased from 5
    icon: 'assets/Items/IronHelmet.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Helmet,
  frost_helmet: {
    id: 'frost_helmet',
    name: 'Frost Helmet',
    type: 'Helmet',
    description: 'A cold helmet made from Frost Dragon scales.',
    price: 2800,
    stackable: false,
    def: 45, // Increased from 25
    icon: 'assets/Items/FrostHelmet.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Helmet,
  // Aetheria Materials
  wind_essence: {
    id: 'wind_essence',
    name: 'Wind Essence',
    type: 'Material',
    description: 'Pure wind power extracted from the core of a Sky Wisp.',
    price: 180,
    stackable: true,
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  },
  cloud_crystal: {
    id: 'cloud_crystal',
    name: 'Cloud Crystal',
    type: 'Material',
    description: 'Crystallized water vapor from a Cloud Guardian.',
    price: 250,
    stackable: true,
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  },
  storm_core: {
    id: 'storm_core',
    name: 'Storm Core',
    type: 'Material',
    description:
      'A lump of energy obtained from the center of a Storm Elemental.',
    price: 400,
    stackable: true,
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  },
  lightning_shard: {
    id: 'lightning_shard',
    name: 'Lightning Shard',
    type: 'Material',
    description: 'A shard of solidified lightning. It tingles when touched.',
    price: 320,
    stackable: true,
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  },
  drake_scale: {
    id: 'drake_scale',
    name: 'Drake Scale',
    type: 'Material',
    description: 'Beautiful purple scales of an Aether Drake.',
    price: 600,
    stackable: true,
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  },
  aether_gem: {
    id: 'aether_gem',
    name: 'Aether Gem',
    type: 'Material',
    description: 'A rare gem condensed from the pure magic energy of Aetheria.',
    price: 800,
    stackable: true,
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  },
  architect_core: {
    id: 'architect_core',
    name: "Architect's Core",
    type: 'Material',
    description:
      'A core component of the Celestial Architect. It contains the power to manipulate space.',
    price: 8000,
    stackable: true,
    size: { x: 20, y: 20 },
    worldSize: { x: 76, y: 96 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  },
  // Aetheria Equipment
  wind_blade: {
    id: 'wind_blade',
    name: 'Wind Blade',
    type: 'Weapon',
    description: 'A lightweight sword crafted from Wind Essence.',
    price: 1200,
    stackable: false,
    atk: 180,
    range: 130,
    speed: 6.0,
    weaponType: 'Sword',
    swingArc: 85,
    icon: 'assets/Items/WindBlade.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Weapon,
  storm_spear: {
    id: 'storm_spear',
    name: 'Storm Spear',
    type: 'Weapon',
    description: 'A spear imbued with the power of lightning.',
    price: 1800,
    stackable: false,
    atk: 220,
    range: 250,
    speed: 4.8,
    weaponType: 'Spear',
    swingArc: 45,
    icon: 'assets/Items/StormSpear.png',
    size: { x: 40, y: 40 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Weapon,
  celestial_blade: {
    id: 'celestial_blade',
    name: 'Celestial Blade',
    type: 'Weapon',
    description: 'A holy sword used by the Celestial Architect.',
    price: 12000,
    stackable: false,
    atk: 650, // Decreased from 750
    range: 200,
    speed: 7.5,
    weaponType: 'Sword',
    swingArc: 100,
    icon: 'assets/Items/CelestialBlade.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Weapon,
  cloud_armor: {
    id: 'cloud_armor',
    name: 'Cloud Armor',
    type: 'Armor',
    description: 'Lightweight armor made from Cloud Crystals.',
    price: 2200,
    stackable: false,
    def: 35,
    icon: 'assets/Items/CloudArmor.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Armor,
  storm_mail: {
    id: 'storm_mail',
    name: 'Storm Mail',
    type: 'Armor',
    description: 'Chainmail enhanced by the power of lightning.',
    price: 3500,
    stackable: false,
    def: 45,
    icon: 'assets/Items/StormMail.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Armor,
  sky_weaver_robe: {
    id: 'sky_weaver_robe',
    name: 'Sky Weaver Robe',
    type: 'Armor',
    description: 'A divine robe worn by the Celestial Architect.',
    price: 15000,
    stackable: false,
    def: 120, // Increased from 80
    icon: 'assets/Items/SkyWeaverRobe.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Armor,
  wind_circlet: {
    id: 'wind_circlet',
    name: 'Wind Circlet',
    type: 'Helmet',
    description: 'A lightweight headpiece made from Wind Essence.',
    price: 800,
    stackable: false,
    def: 12,
    icon: 'assets/Items/WindCirclet.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Helmet,
  storm_crown: {
    id: 'storm_crown',
    name: 'Storm Crown',
    type: 'Helmet',
    description: 'A crown imbued with the power of a Storm Elemental.',
    price: 2800,
    stackable: false,
    def: 40, // Increased from 22
    icon: 'assets/Items/StormCrown.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Helmet,

  // Boss Set Item - Celestial Architect Set
  celestial_crown: {
    id: 'celestial_crown',
    name: 'Celestial Crown',
    type: 'Helmet',
    description: 'A holy crown used by the Celestial Architect.',
    price: 20000,
    stackable: false,
    def: 60, // Increased from 35
    icon: 'assets/Items/CelestialCrown.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Helmet,

  // Boss Set Item - Ignis Overlord Set (Future)
  inferno_blade: {
    id: 'inferno_blade',
    name: 'Inferno Blade',
    type: 'Weapon',
    description: 'A powerful sword containing the heat of lava.',
    price: 25000,
    stackable: false,
    atk: 450,
    range: 160,
    speed: 5.5,
    weaponType: 'Sword',
    swingArc: 90,
    icon: 'assets/Items/InfernoBlade.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Weapon,

  magma_armor: {
    id: 'magma_armor',
    name: 'Magma Armor',
    type: 'Armor',
    description: 'Powerful armor forged from magma.',
    price: 22000,
    stackable: false,
    def: 130, // Increased from 90
    icon: 'assets/Items/MagmaArmor.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Armor,

  inferno_crown: {
    id: 'inferno_crown',
    name: 'Inferno Crown',
    type: 'Helmet',
    description: 'A crown containing the heat of Ignis.',
    price: 18000,
    stackable: false,
    def: 40,
    icon: 'assets/Items/InfernoCrown.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Helmet,

  // Boss Set Item - Xylos Sovereign Set (Future)
  jungle_blade: {
    id: 'jungle_blade',
    name: 'Jungle Blade',
    type: 'Weapon',
    description: 'A mysterious sword used by the Jungle King.',
    price: 35000,
    stackable: false,
    atk: 550,
    range: 170,
    speed: 6.0,
    weaponType: 'Sword',
    swingArc: 95,
    icon: 'assets/Items/JungleBlade.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Weapon,

  jungle_armor: {
    id: 'jungle_armor',
    name: 'Jungle Armor',
    type: 'Armor',
    description: 'Armor filled with the vitality of the jungle.',
    price: 32000,
    stackable: false,
    def: 160, // Increased from 110
    icon: 'assets/Items/JungleArmor.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Armor,

  jungle_crown: {
    id: 'jungle_crown',
    name: 'Jungle Crown',
    type: 'Helmet',
    description: 'A holy crown used by the Jungle King.',
    price: 28000,
    stackable: false,
    def: 50,
    icon: 'assets/Items/JungleCrown.png',
    size: { x: 32, y: 32 },
    worldSize: { x: 128, y: 128 },
    inventorySize: { x: 128, y: 128 },
    quickBarSize: { x: 54, y: 54 },
  } as Helmet,
};

export const WEAPON_DATABASE = ITEM_DATABASE;
