import type { MapData } from './game';

export const WORLD_DATABASE: Record<string, MapData> = {
  town: {
    id: 'town',
    name: '평화로운 마을',
    bgColor: '#1a2a1a',
    canSpawnMonsters: false,
    portals: [
      {
        id: 't-to-m',
        x: 1190,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'meadow',
        targetX: 100,
        targetY: 960 / 2,
      },
      {
        id: 't-to-ss',
        x: 20,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'star_station',
        targetX: 1280 - 150,
        targetY: 960 / 2,
      },
    ],
    npcs: [
      {
        id: 'merchant_town',
        name: '상점 주인 벤',
        type: 'Merchant',
        position: { x: 250, y: 300 },
        size: { x: 220, y: 280 },
        nameOffset: { x: -5, y: -80 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        shopItems: [
          'iron_sword',
          'red_potion',
          'blue_potion',
          'old_armor',
          'return_scroll',
        ],
      },
      {
        id: 'blacksmith_town',
        name: '대장장이 오르손',
        type: 'Blacksmith',
        position: { x: 400, y: 300 },
        size: { x: 200, y: 280 },
        nameOffset: { x: 5, y: -80 },
        velocity: { x: 0, y: 0 },
        speed: 0,
      },
    ],
  },

  meadow: {
    id: 'meadow',
    name: '슬라임 초원',
    bgColor: '#111811', // Darker green for combat
    canSpawnMonsters: true,
    portals: [
      {
        id: 'm-to-t',
        x: 20,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'town',
        targetX: 1280 - 120,
        targetY: 960 / 2,
      },
      {
        id: 'm-to-f',
        x: 1280 / 2 - 50,
        y: 20,
        width: 100,
        height: 40,
        targetMapId: 'forest',
        targetX: 1280 / 2,
        targetY: 960 - 100,
      },
    ],
    npcs: [],
  },
  forest: {
    id: 'forest',
    name: '고블린 숲',
    bgColor: '#0d1a0d',
    canSpawnMonsters: true,
    portals: [
      {
        id: 'f-to-m',
        x: 1280 / 2 - 50,
        y: 960 - 60,
        width: 100,
        height: 40,
        targetMapId: 'meadow',
        targetX: 1280 / 2,
        targetY: 100,
      },
      {
        id: 'f-to-c',
        x: 1280 - 60,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'cave',
        targetX: 100,
        targetY: 960 / 2,
      },
    ],
    npcs: [],
  },
  cave: {
    id: 'cave',
    name: '어두운 동굴',
    bgColor: '#1a1a1a',
    canSpawnMonsters: true,
    portals: [
      {
        id: 'c-to-f',
        x: 20,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'forest',
        targetX: 1280 - 120,
        targetY: 960 / 2,
      },
      {
        id: 'c-to-fc',
        x: 1280 - 60,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'frozen_cliff',
        targetX: 100,
        targetY: 960 / 2,
      },
    ],
    npcs: [],
  },
  frozen_cliff: {
    id: 'frozen_cliff',
    name: '얼어붙은 절벽',
    bgColor: '#e0f7fa',
    canSpawnMonsters: true,
    portals: [
      {
        id: 'fc-to-c',
        x: 20,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'cave',
        targetX: 1280 - 120,
        targetY: 960 / 2,
      },
      {
        id: 'fc-to-ic',
        x: 1280 / 2 - 50,
        y: 20,
        width: 100,
        height: 40,
        targetMapId: 'ice_cave',
        targetX: 1280 / 2,
        targetY: 960 - 100,
      },
    ],
    npcs: [],
  },
  ice_cave: {
    id: 'ice_cave',
    name: '얼음 동굴',
    bgColor: '#3e2723',
    canSpawnMonsters: true,
    portals: [
      {
        id: 'ic-to-fc',
        x: 1280 / 2 - 50,
        y: 960 - 60,
        width: 100,
        height: 40,
        targetMapId: 'frozen_cliff',
        targetX: 1280 / 2,
        targetY: 100,
      },
    ],
    npcs: [],
  },

  star_station: {
    id: 'star_station',
    name: '별무리 정거장',
    bgColor: '#0a0a1a',
    canSpawnMonsters: false,
    portals: [
      {
        id: 'ss-to-t',
        x: 1280 - 60,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'town',
        targetX: 150,
        targetY: 960 / 2,
      },
    ],
    npcs: [
      {
        id: 'exploration_spaceship',
        name: '은하 탐사선',
        type: 'Spaceship',
        position: { x: 640, y: 480 },
        size: { x: 120, y: 160 },
        velocity: { x: 0, y: 0 },
        speed: 0,
      },
      {
        id: 'station_guide',
        name: '정거장 안내원 Ai',
        type: 'Guide',
        position: { x: 800, y: 480 },
        size: { x: 60, y: 100 },
        nameOffset: { x: 0, y: -80 },
        velocity: { x: 0, y: 0 },
        speed: 0,
      },
    ],
  },
  proxima_luna: {
    id: 'proxima_luna',
    name: '프록시마 루나',
    bgColor: '#000033',
    canSpawnMonsters: true,
    portals: [
      {
        id: 'luna-to-ss',
        x: 1280 / 2 - 50,
        y: 960 - 60,
        width: 100,
        height: 40,
        targetMapId: 'star_station',
        targetX: 640,
        targetY: 600,
      },
    ],
    npcs: [],
  },
  aetheria: {
    id: 'aetheria',
    name: '에테리아',
    bgColor: '#b3e5fc',
    canSpawnMonsters: true,
    portals: [
      {
        id: 'aeth-to-ss',
        x: 1280 / 2 - 50,
        y: 960 - 60,
        width: 100,
        height: 40,
        targetMapId: 'star_station',
        targetX: 640,
        targetY: 600,
      },
    ],
    npcs: [],
  },
  ignis_prime: {
    id: 'ignis_prime',
    name: '이그니스 프라임',
    bgColor: '#4e342e',
    canSpawnMonsters: true,
    portals: [
      {
        id: 'ignis-to-ss',
        x: 1280 / 2 - 50,
        y: 960 - 60,
        width: 100,
        height: 40,
        targetMapId: 'star_station',
        targetX: 640,
        targetY: 600,
      },
    ],
    npcs: [],
  },
  xylos: {
    id: 'xylos',
    name: '자일로스',
    bgColor: '#1b5e20',
    canSpawnMonsters: true,
    portals: [
      {
        id: 'xylos-to-ss',
        x: 1280 / 2 - 50,
        y: 960 - 60,
        width: 100,
        height: 40,
        targetMapId: 'star_station',
        targetX: 640,
        targetY: 600,
      },
    ],
    npcs: [],
  },
};
