import type { MapData } from './game';

export const WORLD_DATABASE: Record<string, MapData> = {
  town: {
    id: 'town',
    name: 'Peaceful Village',
    bgColor: '#1a2a1a',
    canSpawnMonsters: false,
    portals: [
      {
        id: 't-to-m',
        x: 1190,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'meadow',
        targetX: 100,
        targetY: 960 / 2,
      },
      {
        id: 't-to-ss',
        x: 20,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'star_station',
        targetX: 1280 - 150,
        targetY: 960 / 2,
      },
    ],
    npcs: [
      {
        id: 'merchant_town',
        name: 'Merchant',
        type: 'Merchant',
        position: { x: 250, y: 300 },
        size: { x: 220, y: 270 },
        nameOffset: { x: -5, y: -80 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        shopItems: [
          'iron_sword',
          'red_potion',
          'blue_potion',
          'old_armor',
          'leather_cap',
          'iron_helmet',
          'return_scroll',
        ],
      },
      {
        id: 'blacksmith_town',
        name: 'Blacksmith',
        type: 'Blacksmith',
        position: { x: 400, y: 300 },
        size: { x: 250, y: 300 },
        nameOffset: { x: 5, y: -90 },
        velocity: { x: 0, y: 0 },
        speed: 0,
      },
      {
        id: 'village_head',
        name: 'Village Head',
        type: 'Quest',
        position: { x: 550, y: 250 },
        size: { x: 250, y: 270 },
        nameOffset: { x: 0, y: -100 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        spriteUrl: 'assets/Npc/village_head.png',
        dialogues: [
          'Welcome to our peaceful village.',
          'The world outside has become quite dangerous lately.',
          'If you need anything, please talk to the merchants.',
          'Good luck on your journey, traveler.',
        ],
      },
      {
        id: 'town_cat',
        name: 'Town Cat',
        type: 'Quest',
        position: { x: 700, y: 300 },
        size: { x: 128, y: 128 },
        nameOffset: { x: 0, y: -40 },
        velocity: { x: 0, y: 0 },
        spriteUrl: 'assets/Npc/town_cat.png',
        speed: 0,
        dialogues: [
          'Meow...',
          '(The cat seems to be enjoying the sunlight.)',
          'Purr...',
          'Meow! (It wants a treats?)',
        ],
      },
      {
        id: 'town_sign',
        name: 'Town Sign',
        type: 'Quest',
        position: { x: 900, y: 350 },
        size: { x: 128, y: 128 },
        nameOffset: { x: 0, y: -60 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        dialogueMode: 'sequential',
        dialogues: [
          'Welcome to Peaceful Village.',
          'East: Slime Grasslands',
          'West: Star Station',
        ],
      },
    ],
    fixedSpawns: [
      { monsterId: 'training_dummy', x: 895, y: 200 },
      { monsterId: 'training_dummy', x: 1025, y: 200 },
    ],
  },

  meadow: {
    id: 'meadow',
    name: 'Slime Grasslands',
    bgColor: '#111811', // Darker green for combat
    canSpawnMonsters: true,
    spawnInterval: 1, // spawn every 1 second
    portals: [
      {
        id: 'm-to-t',
        x: 20,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'town',
        targetX: 1280 - 120,
        targetY: 960 / 2,
      },
      {
        id: 'm-to-f',
        x: 1280 / 2 - 50,
        y: 20,
        width: 100,
        height: 40,
        targetMapId: 'forest',
        targetX: 1280 / 2,
        targetY: 960 - 100,
      },
    ],
    npcs: [],
  },
  forest: {
    id: 'forest',
    name: 'Goblin Forest',
    bgColor: '#0d1a0d',
    canSpawnMonsters: true,
    spawnInterval: 1, // spawn every 6 seconds
    portals: [
      {
        id: 'f-to-m',
        x: 1280 / 2 - 50,
        y: 960 - 60,
        width: 100,
        height: 40,
        targetMapId: 'meadow',
        targetX: 1280 / 2,
        targetY: 100,
      },
      {
        id: 'f-to-c',
        x: 1280 - 60,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'cave',
        targetX: 100,
        targetY: 960 / 2,
      },
    ],
    npcs: [],
  },
  cave: {
    id: 'cave',
    name: 'Dark Cave',
    bgColor: '#1a1a1a',
    canSpawnMonsters: true,
    spawnInterval: 0.3, // spawn every 8 seconds
    portals: [
      {
        id: 'c-to-f',
        x: 20,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'forest',
        targetX: 1280 - 120,
        targetY: 960 / 2,
      },
      {
        id: 'c-to-fc',
        x: 1280 - 60,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'frozen_cliff',
        targetX: 100,
        targetY: 960 / 2,
      },
    ],
    npcs: [],
  },
  frozen_cliff: {
    id: 'frozen_cliff',
    name: 'Frozen Cliff',
    bgColor: '#e0f7fa',
    canSpawnMonsters: true,
    spawnInterval: 2, // spawn every 2 seconds
    portals: [
      {
        id: 'fc-to-c',
        x: 20,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'cave',
        targetX: 1280 - 120,
        targetY: 960 / 2,
      },
      {
        id: 'fc-to-ic',
        x: 1280 / 2 - 50,
        y: 20,
        width: 100,
        height: 40,
        targetMapId: 'ice_cave',
        targetX: 1280 / 2,
        targetY: 960 - 100,
      },
    ],
    npcs: [],
  },
  ice_cave: {
    id: 'ice_cave',
    name: 'Ice Cave',
    bgColor: '#3e2723',
    canSpawnMonsters: true,
    portals: [
      {
        id: 'ic-to-fc',
        x: 1280 / 2 - 50,
        y: 960 - 60,
        width: 100,
        height: 40,
        targetMapId: 'frozen_cliff',
        targetX: 1280 / 2,
        targetY: 100,
      },
    ],
    npcs: [],
  },

  star_station: {
    id: 'star_station',
    name: 'Stellar Station',
    bgColor: '#0a0a1a',
    canSpawnMonsters: false,
    portals: [
      {
        id: 'ss-to-t',
        x: 1280 - 60,
        y: 960 / 2 - 50,
        width: 40,
        height: 100,
        targetMapId: 'town',
        targetX: 150,
        targetY: 960 / 2,
      },
      {
        id: 'ss-to-pl',
        x: 640 - 50,
        y: 20,
        width: 100,
        height: 60,
        targetMapId: 'proxima_station',
        targetX: 640,
        targetY: 850,
        requiredBossId: 'frost_dragon',
      },
      {
        id: 'ss-to-aeth',
        x: 640 - 50,
        y: 900,
        width: 100,
        height: 60,
        targetMapId: 'aetheria',
        targetX: 640,
        targetY: 850,
        requiredBossId: 'luna_overseer',
      },
    ],
    npcs: [
      {
        id: 'exploration_spaceship',
        name: 'Galactic Explorer',
        type: 'Spaceship',
        position: { x: 640, y: 480 },
        size: { x: 120, y: 160 },
        velocity: { x: 0, y: 0 },
        speed: 0,
      },
      {
        id: 'station_guide',
        name: 'Station Guide AI',
        type: 'Guide',
        position: { x: 800, y: 480 },
        size: { x: 60, y: 100 },
        nameOffset: { x: 0, y: -80 },
        velocity: { x: 0, y: 0 },
        speed: 0,
      },
    ],
  },
  proxima_station: {
    id: 'proxima_station',
    name: 'Proxima Station',
    bgColor: '#050525',
    canSpawnMonsters: false,
    portals: [
      {
        id: 'ps-to-ss',
        x: 640 - 50,
        y: 960 - 60,
        width: 100,
        height: 60,
        targetMapId: 'star_station',
        targetX: 640,
        targetY: 800,
      },
      {
        id: 'ps-to-pp',
        x: 20,
        y: 480 - 50,
        width: 60,
        height: 100,
        targetMapId: 'proxima_plains',
        targetX: 1100,
        targetY: 480,
      },
      {
        id: 'ps-to-pr',
        x: 1220,
        y: 480 - 50,
        width: 60,
        height: 100,
        targetMapId: 'proxima_ruins',
        targetX: 100,
        targetY: 480,
      },
      {
        id: 'ps-to-pv',
        x: 640 - 50,
        y: 20,
        width: 100,
        height: 60,
        targetMapId: 'proxima_void',
        targetX: 640,
        targetY: 850,
      },
    ],
    npcs: [
      {
        id: 'robot-rx7',
        name: 'Exploration Robot RX-7',
        type: 'Merchant',
        position: { x: 640, y: 480 },
        size: { x: 240, y: 290 },
        nameOffset: { x: 0, y: -80 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        spriteUrl: 'assets/Npc/Robot_RX7.png',
        shopItems: [
          'pulse_blade',
          'titanium_armor',
          'luna_goggles',
          'enhance_stone',
          'red_potion',
          'blue_potion',
        ],
      },
    ],
  },
  proxima_plains: {
    id: 'proxima_plains',
    name: 'Moon Plains',
    bgColor: '#02021a',
    canSpawnMonsters: true,
    spawnInterval: 1.5,
    portals: [
      {
        id: 'pp-to-ps',
        x: 1220,
        y: 480 - 50,
        width: 60,
        height: 100,
        targetMapId: 'proxima_station',
        targetX: 100,
        targetY: 480,
      },
    ],
    npcs: [],
  },
  proxima_ruins: {
    id: 'proxima_ruins',
    name: 'Lunar Ruins',
    bgColor: '#0a0a20',
    canSpawnMonsters: true,
    spawnInterval: 3,
    portals: [
      {
        id: 'pr-to-ps',
        x: 20,
        y: 480 - 50,
        width: 60,
        height: 100,
        targetMapId: 'proxima_station',
        targetX: 1100,
        targetY: 480,
      },
      {
        id: 'pr-to-pc',
        x: 640 - 50,
        y: 20,
        width: 100,
        height: 60,
        targetMapId: 'proxima_core',
        targetX: 640,
        targetY: 850,
      },
    ],
    npcs: [],
  },
  proxima_void: {
    id: 'proxima_void',
    name: 'Lunar Void',
    bgColor: '#00000a',
    canSpawnMonsters: true,
    spawnInterval: 2,
    portals: [
      {
        id: 'pv-to-ps',
        x: 640 - 50,
        y: 900,
        width: 100,
        height: 60,
        targetMapId: 'proxima_station',
        targetX: 640,
        targetY: 100,
      },
    ],
    npcs: [],
  },
  proxima_core: {
    id: 'proxima_core',
    name: 'Lunar Core',
    bgColor: '#150015',
    canSpawnMonsters: true,
    spawnInterval: 2,
    portals: [
      {
        id: 'pc-to-pr',
        x: 640 - 50,
        y: 900,
        width: 100,
        height: 60,
        targetMapId: 'proxima_ruins',
        targetX: 640,
        targetY: 100,
      },
    ],
    npcs: [],
  },
  aetheria: {
    id: 'aetheria',
    name: 'Aetheria',
    bgColor: '#b3e5fc',
    canSpawnMonsters: false,
    portals: [
      {
        id: 'aeth-to-ss',
        x: 1280 / 2 - 50,
        y: 960 - 60,
        width: 100,
        height: 40,
        targetMapId: 'star_station',
        targetX: 640,
        targetY: 600,
      },
      {
        id: 'aeth-to-upper',
        x: 1280 / 2 - 50,
        y: 20,
        width: 100,
        height: 40,
        targetMapId: 'aetheria_upper',
        targetX: 640,
        targetY: 850,
      },
      {
        id: 'aeth-to-gardens',
        x: 20,
        y: 480 - 50,
        width: 40,
        height: 100,
        targetMapId: 'sky_gardens',
        targetX: 1200,
        targetY: 480,
      },
      {
        id: 'aeth-to-workshop',
        x: 1240,
        y: 480 - 50,
        width: 40,
        height: 100,
        targetMapId: 'wind_workshop',
        targetX: 80,
        targetY: 480,
      },
    ],
    npcs: [
      {
        id: 'wind_merchant',
        name: 'Wind Merchant',
        type: 'Merchant',
        position: { x: 640, y: 400 },
        size: { x: 200, y: 250 },
        nameOffset: { x: 0, y: -80 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        spriteUrl: 'assets/Npc/WindMerchant.png',
        shopItems: [
          'wind_blade',
          'cloud_armor',
          'wind_circlet',
          'red_potion',
          'blue_potion',
          'wind_essence',
        ],
        dialogues: [
          'The winds are strong today.',
          'Would you like to see my collection of rare items?',
          'Safe travels through the clouds.',
          'Come back anytime!',
          'May the gale guide you.',
        ],
      },
      {
        id: 'sky_sage',
        name: 'Sky Sage',
        type: 'Quest',
        position: { x: 500, y: 350 },
        size: { x: 180, y: 220 },
        nameOffset: { x: 0, y: -90 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        spriteUrl: 'assets/Npc/SkySage.png',
        dialogues: [
          'Patience is the key to wisdom.',
          'Aetheria holds many secrets.',
          'Observe the stars, and you shall find the way.',
          'The ancient architect left us a legacy.',
          'Knowledge is power, young one.',
          'Be careful in the Mystic Grove.',
        ],
      },
      {
        id: 'crystal_researcher',
        name: 'Crystal Researcher',
        type: 'Quest',
        position: { x: 780, y: 380 },
        size: { x: 160, y: 200 },
        nameOffset: { x: 0, y: -70 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        spriteUrl: 'assets/Npc/CrystalResearcher.png',
        dialogues: [
          'These crystals hum with an interesting frequency.',
          'I need more samples from the forge.',
          'Do you have any spare aether gems?',
          'Nature and magic are one in this place.',
          'Fascinating... simply fascinating.',
        ],
      },
    ],
  },
  sky_gardens: {
    id: 'sky_gardens',
    name: 'Sky Gardens',
    bgColor: '#e8f5e8',
    canSpawnMonsters: true,
    spawnInterval: 10,
    portals: [
      {
        id: 'sg-to-aeth',
        x: 1240,
        y: 480 - 50,
        width: 40,
        height: 100,
        targetMapId: 'aetheria',
        targetX: 80,
        targetY: 480,
      },
      {
        id: 'sg-to-grove',
        x: 640 - 50,
        y: 20,
        width: 100,
        height: 40,
        targetMapId: 'mystic_grove',
        targetX: 640,
        targetY: 880,
      },
    ],
    npcs: [],
    fixedSpawns: [
      { monsterId: 'sky_wisp', x: 300, y: 300, level: 110 },
      { monsterId: 'cloud_guardian', x: 800, y: 600, level: 110 },
    ],
  },
  wind_workshop: {
    id: 'wind_workshop',
    name: 'Wind Workshop',
    bgColor: '#f0f4f8',
    canSpawnMonsters: false,
    portals: [
      {
        id: 'ww-to-aeth',
        x: 20,
        y: 480 - 50,
        width: 40,
        height: 100,
        targetMapId: 'aetheria',
        targetX: 1200,
        targetY: 480,
      },
      {
        id: 'ww-to-forge',
        x: 640 - 50,
        y: 20,
        width: 100,
        height: 40,
        targetMapId: 'crystal_forge',
        targetX: 640,
        targetY: 880,
      },
      {
        id: 'ww-to-hunting',
        x: 1240,
        y: 480 - 50,
        width: 40,
        height: 100,
        targetMapId: 'wind_hunting_grounds',
        targetX: 80,
        targetY: 480,
      },
    ],
    npcs: [
      {
        id: 'master_craftsman',
        name: 'Master Craftsman',
        type: 'Blacksmith',
        position: { x: 640, y: 480 },
        size: { x: 420, y: 480 },
        nameOffset: { x: 15, y: -120 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        spriteUrl: 'assets/Npc/MasterCraftsman.png',
        dialogues: [
          'A blade is only as good as the soul who wields it.',
          'I can make anything if you have the materials.',
          'Focus on your craft.',
          'The workshop is always open for those who seek to create.',
        ],
      },
      {
        id: 'wind_apprentice',
        name: 'Wind Apprentice',
        type: 'Quest',
        position: { x: 400, y: 600 },
        size: { x: 160, y: 200 },
        nameOffset: { x: 0, y: -70 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        spriteUrl: 'assets/Npc/WindApprentice.png',
        dialogues: [
          'I still have so much to learn.',
          'Master is very strict, but he is the best.',
          'Have you seen any rare materials lately?',
          'Someday, I will craft a legendary sword.',
        ],
      },
    ],
  },
  mystic_grove: {
    id: 'mystic_grove',
    name: 'Mystic Forest',
    bgColor: '#2d5a2d',
    canSpawnMonsters: true,
    spawnInterval: 6,
    portals: [
      {
        id: 'mg-to-sg',
        x: 640 - 50,
        y: 920,
        width: 100,
        height: 40,
        targetMapId: 'sky_gardens',
        targetX: 640,
        targetY: 80,
      },
    ],
    npcs: [
      {
        id: 'ancient_treant',
        name: 'Ancient Treant',
        type: 'Quest',
        position: { x: 640, y: 480 },
        size: { x: 250, y: 300 },
        nameOffset: { x: 0, y: -120 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        spriteUrl: 'assets/Npc/AncientTreant.png',
        dialogues: [
          'I have seen centuries pass like autumn leaves.',
          'The forest mourns for the lost ones.',
          'Nature will reclaim what was taken.',
          'Speak softly, traveler.',
          'May the roots hold you steady.',
        ],
      },
    ],
    fixedSpawns: [
      { monsterId: 'cloud_guardian', x: 300, y: 300, level: 150 },
      { monsterId: 'storm_elemental', x: 800, y: 600, level: 150 },
      { monsterId: 'aether_drake', x: 640, y: 200, level: 160 },
    ],
  },
  crystal_forge: {
    id: 'crystal_forge',
    name: 'Crystal Forge',
    bgColor: '#4a148c',
    canSpawnMonsters: false,
    portals: [
      {
        id: 'cf-to-ww',
        x: 640 - 50,
        y: 920,
        width: 100,
        height: 40,
        targetMapId: 'wind_workshop',
        targetX: 640,
        targetY: 80,
      },
      {
        id: 'cf-to-caves',
        x: 20,
        y: 480 - 50,
        width: 40,
        height: 100,
        targetMapId: 'crystal_caves',
        targetX: 1200,
        targetY: 480,
      },
      {
        id: 'cf-to-depths',
        x: 1240,
        y: 480 - 50,
        width: 40,
        height: 100,
        targetMapId: 'forge_depths',
        targetX: 80,
        targetY: 480,
      },
    ],
    npcs: [
      {
        id: 'crystal_master',
        name: 'Crystal Master',
        type: 'Blacksmith',
        position: { x: 640, y: 480 },
        size: { x: 420, y: 480 },
        nameOffset: { x: 15, y: -120 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        spriteUrl: 'assets/Npc/CrystalMaster.png',
        shopItems: [
          'storm_spear',
          'storm_mail',
          'storm_crown',
          'enhance_stone',
          'aether_gem',
        ],
        dialogues: [
          'The crystals here are pure and powerful.',
          'I can forge the strongest equipment with these.',
          'Bring me Aether Gems if you want the best.',
          'The forge never sleeps.',
        ],
      },
    ],
  },
  crystal_caves: {
    id: 'crystal_caves',
    name: 'Crystal Caves',
    bgColor: '#1a0d26',
    canSpawnMonsters: true,
    spawnInterval: 8,
    portals: [
      {
        id: 'cc-to-cf',
        x: 1240,
        y: 480 - 50,
        width: 40,
        height: 100,
        targetMapId: 'crystal_forge',
        targetX: 80,
        targetY: 480,
      },
    ],
    npcs: [],
    fixedSpawns: [
      { monsterId: 'cloud_guardian', x: 300, y: 300, level: 200 },
      { monsterId: 'storm_elemental', x: 600, y: 200, level: 200 },
      { monsterId: 'aether_drake', x: 900, y: 700, level: 200 },
    ],
  },
  aetheria_upper: {
    id: 'aetheria_upper',
    name: 'Aetheria Upper',
    bgColor: '#e1f5fe',
    canSpawnMonsters: true,
    spawnInterval: 12,
    portals: [
      {
        id: 'au-to-aeth',
        x: 1280 / 2 - 50,
        y: 900,
        width: 100,
        height: 60,
        targetMapId: 'aetheria',
        targetX: 640,
        targetY: 100,
      },
      {
        id: 'au-to-sanctum',
        x: 1280 / 2 - 50,
        y: 20,
        width: 100,
        height: 40,
        targetMapId: 'celestial_sanctum',
        targetX: 640,
        targetY: 850,
      },
      {
        id: 'au-to-observatory',
        x: 20,
        y: 480 - 50,
        width: 40,
        height: 100,
        targetMapId: 'star_observatory',
        targetX: 1200,
        targetY: 480,
      },
    ],
    npcs: [
      {
        id: 'storm_blacksmith',
        name: 'Storm Blacksmith',
        type: 'Blacksmith',
        position: { x: 640, y: 480 },
        size: { x: 220, y: 280 },
        nameOffset: { x: 0, y: -100 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        dialogues: [
          'Can you hear the thunder?',
          'My hammer moves with the lightning.',
          'Forging in the storm requires great focus.',
          'Behold the power of the sky!',
        ],
      },
      {
        id: 'wind_guardian',
        name: 'Wind Guardian',
        type: 'Quest',
        position: { x: 400, y: 400 },
        size: { x: 200, y: 250 },
        nameOffset: { x: 0, y: -90 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        dialogues: [
          'Only those with a pure heart may pass.',
          'The winds protect this sacred place.',
          'Are you a friend or a foe of Aetheria?',
          'The architect is watching.',
          'May your spirit fly high.',
        ],
      },
    ],
    fixedSpawns: [
      { monsterId: 'storm_elemental', x: 300, y: 300, level: 250 },
      { monsterId: 'aether_drake', x: 900, y: 400, level: 250 },
    ],
  },
  star_observatory: {
    id: 'star_observatory',
    name: 'Star Observatory',
    bgColor: '#0d1421',
    canSpawnMonsters: true,
    spawnInterval: 18,
    portals: [
      {
        id: 'so-to-au',
        x: 1240,
        y: 480 - 50,
        width: 40,
        height: 100,
        targetMapId: 'aetheria_upper',
        targetX: 80,
        targetY: 480,
      },
    ],
    npcs: [
      {
        id: 'star_astronomer',
        name: 'Star Astronomer',
        type: 'Quest',
        position: { x: 640, y: 480 },
        size: { x: 180, y: 220 },
        nameOffset: { x: 0, y: -90 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        dialogues: [
          'The alignment of the stars is strange today.',
          'I see a great destiny in your path.',
          'The cosmic energy is flowing through everything.',
          'Have you looked through the telescope?',
          'The universe is vast and full of wonders.',
        ],
      },
      {
        id: 'cosmic_merchant',
        name: 'Cosmic Merchant',
        type: 'Merchant',
        position: { x: 400, y: 400 },
        size: { x: 200, y: 250 },
        nameOffset: { x: 0, y: -80 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        shopItems: [
          'celestial_blade',
          'sky_weaver_robe',
          'aether_gem',
          'architect_core',
          'enhance_stone',
        ],
        dialogues: [
          'Rare goods from across the galaxy!',
          'Interested in some celestial artifacts?',
          'My prices are out of this world!',
        ],
      },
    ],
    fixedSpawns: [
      { monsterId: 'aether_drake', x: 300, y: 300, level: 300 },
      { monsterId: 'storm_elemental', x: 800, y: 600, level: 300 },
    ],
  },
  celestial_sanctum: {
    id: 'celestial_sanctum',
    name: 'Celestial Sanctum',
    bgColor: '#f3e5f5',
    canSpawnMonsters: true,
    spawnInterval: 20,
    portals: [
      {
        id: 'cs-to-au',
        x: 1280 / 2 - 50,
        y: 900,
        width: 100,
        height: 60,
        targetMapId: 'aetheria_upper',
        targetX: 640,
        targetY: 100,
      },
    ],
    npcs: [
      {
        id: 'architect_altar',
        name: 'Architect Altar',
        type: 'Quest',
        position: { x: 640, y: 300 },
        size: { x: 150, y: 100 },
        nameOffset: { x: 0, y: -60 },
        velocity: { x: 0, y: 0 },
        speed: 0,
        dialogueMode: 'sequential',
        dialogues: [
          '(An ancient altar dedicated to the Celestial Architect.)',
          '(It glows with a faint, divine light.)',
          '(You feel a strange presence nearby...)',
        ],
      },
    ],
    fixedSpawns: [
      { monsterId: 'celestial_architect', x: 640, y: 480, level: 400 },
    ],
  },
  ignis_prime: {
    id: 'ignis_prime',
    name: 'Ignis Prime',
    bgColor: '#4e342e',
    canSpawnMonsters: true,
    spawnInterval: 8,
    portals: [
      {
        id: 'ignis-to-ss',
        x: 1280 / 2 - 50,
        y: 960 - 60,
        width: 100,
        height: 40,
        targetMapId: 'star_station',
        targetX: 640,
        targetY: 600,
      },
    ],
    npcs: [],
  },
  wind_hunting_grounds: {
    id: 'wind_hunting_grounds',
    name: 'Wind Hunting Grounds',
    bgColor: '#e1f5fe',
    canSpawnMonsters: true,
    spawnInterval: 8,
    maxMonsters: 10,
    portals: [
      {
        id: 'whg-to-ww',
        x: 20,
        y: 480 - 50,
        width: 40,
        height: 100,
        targetMapId: 'wind_workshop',
        targetX: 1200,
        targetY: 480,
      },
    ],
    npcs: [],
    fixedSpawns: [
      { monsterId: 'sky_wisp', x: 300, y: 300, level: 130 },
      { monsterId: 'storm_elemental', x: 800, y: 600, level: 130 },
      { monsterId: 'sky_wisp', x: 600, y: 200, level: 130 },
    ],
  },
  forge_depths: {
    id: 'forge_depths',
    name: 'Forge Depths',
    bgColor: '#311b92',
    canSpawnMonsters: true,
    spawnInterval: 10,
    maxMonsters: 8,
    portals: [
      {
        id: 'fd-to-cf',
        x: 20,
        y: 480 - 50,
        width: 40,
        height: 100,
        targetMapId: 'crystal_forge',
        targetX: 1200,
        targetY: 480,
      },
    ],
    npcs: [],
    fixedSpawns: [
      { monsterId: 'storm_elemental', x: 300, y: 300, level: 180 },
      { monsterId: 'aether_drake', x: 800, y: 600, level: 180 },
      { monsterId: 'storm_elemental', x: 600, y: 700, level: 180 },
    ],
  },
  xylos: {
    id: 'xylos',
    name: 'Xylos',
    bgColor: '#1b5e20',
    canSpawnMonsters: true,
    spawnInterval: 10,
    portals: [
      {
        id: 'xylos-to-ss',
        x: 1280 / 2 - 50,
        y: 960 - 60,
        width: 100,
        height: 40,
        targetMapId: 'star_station',
        targetX: 640,
        targetY: 600,
      },
    ],
    npcs: [],
  },
};
